version: "3"

services:
  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=rps
      - POSTGRES_USER=rps
      - POSTGRES_PASSWORD=rps

  redis:
    image: redis:5-alpine
    ports:
      - "6379:6379"

  api:
    build: ./api/
    command: sh -c "dockerize -wait tcp://db:5432 && ./manage.py runserver 0.0.0.0:8000"
    environment:
      - RPS_HOSTNAME
    volumes:
      - ./api/:/app/api:rw
    depends_on:
      - db
    ports:
      - "8000:8000"
