version: "3"

services:
  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=rps
      - POSTGRES_USER=rps
      - POSTGRES_PASSWORD=rps

  api:
    build: ./api/
    image: lucaspickering/rps-api:latest
    depends_on:
      - db

  webapp:
    build: ./webapp/
    image: lucaspickering/rps-webapp:latest

  static:
    build: ./
    image: lucaspickering/rps-static:latest
    environment:
      - REACT_APP_GOOGLE_CLIENT_ID
