version: "3"

# Use these instead of the local directory for building the projects
# to prevent the containers from fighting with external build tools
volumes:
  api_poetry_cache:

services:
  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=rps
      - POSTGRES_USER=rps
      - POSTGRES_PASSWORD=rps

  api:
    build: ./slack-api/
    command: sh -c "poetry install && ./m.sh runserver 0.0.0.0:8000"
    init: true # Faster shutdown
    environment:
      - SLACK_CLIENT_ID
      - SLACK_CLIENT_SECRET
      - SLACK_SIGNING_SECRET
    volumes:
      - ./slack-api/:/app/api:rw
      - api_poetry_cache:/root/.cache/poetry
    depends_on:
      - db
    ports:
      - "8000:8000"
