version: "3"

# Use these instead of the local directory for building the projects
# to prevent the containers from fighting with external build tools
volumes:
  api_poetry_cache:

services:
  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=rps
      - POSTGRES_USER=rps
      - POSTGRES_PASSWORD=rps

  redis:
    image: redis:5-alpine
    ports:
      - "6379:6379"

  api:
    build: ./api/
    command: sh -c "poetry install && ./m.sh runserver 0.0.0.0:8000"
    environment:
      - RPS_HOSTNAME
    volumes:
      - ./api/:/app/api:rw
    depends_on:
      - db
    ports:
      - "8000:8000"
