# Generated by Django 2.2.4 on 2019-08-27 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_num', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ('match_id', 'game_num'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LivePlayerMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_activity', models.DateTimeField(auto_now_add=True)),
                ('is_ready', models.BooleanField(default=False)),
                ('move', models.CharField(blank=True, choices=[('rock', 'rock'), ('paper', 'paper'), ('scissors', 'scissors'), ('lizard', 'lizard'), ('spock', 'spock')], max_length=20)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Player')),
            ],
        ),
        migrations.CreateModel(
            name='LivePlayerGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move', models.CharField(choices=[('rock', 'rock'), ('paper', 'paper'), ('scissors', 'scissors'), ('lizard', 'lizard'), ('spock', 'spock')], max_length=20)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livematch.LiveGame')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Player')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LiveMatch',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('best_of', models.PositiveSmallIntegerField(default=5)),
                ('permanent_match', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Match')),
                ('player1', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='match_as_p1', to='livematch.LivePlayerMatch')),
                ('player2', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='match_as_p2', to='livematch.LivePlayerMatch')),
            ],
        ),
        migrations.AddField(
            model_name='livegame',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='livematch.LiveMatch'),
        ),
        migrations.AddField(
            model_name='livegame',
            name='players',
            field=models.ManyToManyField(through='livematch.LivePlayerGame', to='core.Player'),
        ),
        migrations.AddField(
            model_name='livegame',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='livegame_wins', to='core.Player'),
        ),
    ]
