# Generated by Django 2.2.3 on 2019-08-15 00:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_num', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ('game_num',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LivePlayerMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connections', models.PositiveSmallIntegerField(default=0)),
                ('move', models.CharField(blank=True, choices=[('rock', 'rock'), ('paper', 'paper'), ('scissors', 'scissors'), ('lizard', 'lizard'), ('spock', 'spock')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LivePlayerGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move', models.CharField(choices=[('rock', 'rock'), ('paper', 'paper'), ('scissors', 'scissors'), ('lizard', 'lizard'), ('spock', 'spock')], max_length=20)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livematch.LiveGame')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LiveMatch',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('start_time', models.DateField(auto_now=True)),
                ('best_of', models.PositiveSmallIntegerField(default=5)),
                ('player1', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='match_as_p1', to='livematch.LivePlayerMatch')),
                ('player2', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='match_as_p2', to='livematch.LivePlayerMatch')),
            ],
        ),
        migrations.AddField(
            model_name='livegame',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='livematch.LiveMatch'),
        ),
        migrations.AddField(
            model_name='livegame',
            name='players',
            field=models.ManyToManyField(through='livematch.LivePlayerGame', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='livegame',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='livegame_wins', to=settings.AUTH_USER_MODEL),
        ),
    ]
