# Generated by Django 2.2.4 on 2019-08-19 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livematch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveplayermatch',
            name='is_ready',
            field=models.BooleanField(default=False),
        ),
    ]
