# Generated by Django 2.2.4 on 2019-09-03 21:59

import core.util
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livematch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livematch',
            name='best_of',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='livematch',
            name='id',
            field=models.CharField(default=core.util.get_livematch_id, max_length=32, primary_key=True, serialize=False),
        ),
    ]
