# Generated by Django 2.2.3 on 2019-08-09 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('livematch', '0002_livematch_best_of'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveMatchPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connections', models.PositiveSmallIntegerField(default=0)),
                ('move', models.CharField(choices=[('ROCK', 'ROCK'), ('PAPER', 'PAPER'), ('SCISSORS', 'SCISSORS'), ('LIZARD', 'LIZARD'), ('SPOCK', 'SPOCK')], max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='livematch',
            name='player1_is_connected',
        ),
        migrations.RemoveField(
            model_name='livematch',
            name='player1_move',
        ),
        migrations.RemoveField(
            model_name='livematch',
            name='player2_is_connected',
        ),
        migrations.RemoveField(
            model_name='livematch',
            name='player2_move',
        ),
        migrations.AlterField(
            model_name='livematch',
            name='player1',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='match_as_p1', to='livematch.LiveMatchPlayer'),
        ),
        migrations.AlterField(
            model_name='livematch',
            name='player2',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='match_as_p2', to='livematch.LiveMatchPlayer'),
        ),
    ]
