# Generated by Django 2.2.5 on 2019-09-06 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livematch', '0003_livematch_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livematch',
            name='best_of',
        ),
        migrations.RemoveField(
            model_name='livematch',
            name='extended_mode',
        ),
        migrations.AlterField(
            model_name='livematch',
            name='config',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='core.MatchConfig'),
            preserve_default=False,
        ),
    ]
