# Generated by Django 2.2.5 on 2019-09-07 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livematch', '0004_auto_20190906_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='livematch',
            name='rematch',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent', to='livematch.LiveMatch'),
        ),
    ]
