# Generated by Django 2.2.4 on 2019-08-23 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livematch', '0004_auto_20190822_2355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livegame',
            options={'ordering': ('match_id', 'game_num')},
        ),
    ]
