# Generated by Django 2.2.4 on 2019-09-03 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ('-start_time',)},
        ),
    ]
