# Generated by Django 2.2.4 on 2019-08-23 00:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ('match_id', 'game_num')},
        ),
        migrations.AlterField(
            model_name='match',
            name='players',
            field=models.ManyToManyField(related_name='matches', to=settings.AUTH_USER_MODEL),
        ),
    ]
