# Generated by Django 2.2.5 on 2019-09-06 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190903_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_of', models.PositiveSmallIntegerField()),
                ('extended_mode', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.MatchConfig'),
        ),
    ]
