# Generated by Django 2.2.5 on 2019-09-06 22:04

from django.db import migrations
from core.util import Move


def create_match_configs(apps, schema_editor):
    """
    Creates a MatchConfig for each Match in the DB, with the proper values.
    """
    Match = apps.get_model("core", "Match")
    MatchConfig = apps.get_model("core", "MatchConfig")

    for match in Match.objects.prefetch_related(
        "games", "games__playergame_set"
    ).all():
        # If this match have any lizards or spocks played, consider it extended
        all_moves = set()
        for game in match.games.all():
            for pg in game.playergame_set.all():
                all_moves.add(pg.move)
        extended_mode = any(
            move in all_moves for move in (Move.LIZARD.value, Move.SPOCK.value)
        )

        config = MatchConfig.objects.create(
            best_of=match.best_of, extended_mode=extended_mode
        )
        match.config = config
        match.save()


class Migration(migrations.Migration):

    dependencies = [("core", "0003_auto_20190906_2204")]

    operations = [migrations.RunPython(create_match_configs)]
