# Generated by Django 2.2.5 on 2019-09-06 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190906_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='best_of',
        ),
        migrations.AlterField(
            model_name='match',
            name='config',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='core.MatchConfig'),
            preserve_default=False,
        ),
    ]
