# Generated by Django 2.2.5 on 2019-09-16 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190913_0330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playergame',
            options={'ordering': ('id',)},
        ),
    ]
