name: Run tests & push images

on: [push]

jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build API image
        run: docker-compose -f docker-compose.ci.yml build api
      - name: Test API
        run: docker-compose -f docker-compose.ci.yml run api ./docker/run_checks.sh
      - name: Push API image
        if: github.ref == 'refs/heads/master'
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker-compose -f docker-compose.ci.yml push api
  test-webapp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build webapp image
        run: docker-compose -f docker-compose.ci.yml build webapp
      - name: Test webapp
        run: docker-compose -f docker-compose.ci.yml run webapp npm run check
      - name: Push webapp image
        if: github.ref == 'refs/heads/master'
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker-compose -f docker-compose.ci.yml push webapp
  build-static:
    runs-on: ubuntu-latest
    needs:
      - test-api
      - test-webapp
    steps:
      - uses: actions/checkout@master
      - name: Build & push static image
        if: github.ref == 'refs/heads/master'
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          RPS_GOOGLE_CLIENT_ID=${{ secrets.RPS_GOOGLE_CLIENT_ID }} docker-compose -f docker-compose.ci.yml build static
          docker-compose -f docker-compose.ci.yml push static
